### PR TITLE
Set default mode to code

### PR DESCRIPTION
**Pull request by reesericci**
Set the default mode to code to allow for instant editing of the JSON

### CODE REVIEW

**Comment by reesericci** [comment]
PS: this is for the JSON editor

**Comment by deepjyoti30** [comment]
@reesericci I had especially disabled it since everyone might not be familiar with JSON, any reason you think this should be default?

**Comment by reesericci** [comment]
@deepjyoti30

**Comment by reesericci** [comment]
Because you can't edit the JSON in the tree menu.

**Comment by reesericci** [comment]
And also because if you are going into the settings to change the JSON since there is no GUI, it makes sense to have the JSON be front and center

**Comment by deepjyoti30** [comment]
@reesericci It can be changed in the tree view by double clicking any value. I still think the tree view would be more intuitive for the users who are not experienced with JSON.

**Comment by reesericci** [comment]
Oh, just realized that, about to comment. beat me to it

**Comment by reesericci** [comment]
Yeah, let's leave it

**Pull request closed without merging**
