### PR TITLE
Fixed all issues and added nord theme

### PR DESCRIPTION
**Pull request by WitherCubes**
I fixed all my issues from last pull request.

### CODE REVIEW

**Comment by reesericci** [comment]
There is currently no way to select a theme. Which means, this will override the default color scheme. There needs to be a way to pick between black and nord for this to work. @deepjyoti30 what do you say?

**Comment by deepjyoti30** [comment]
@reesericci Yeah. If I merge this PR, it'd override the default colorscheme.

I think the config already allows changing colorschemes? If the end user wants nord theme, they can just copy @WitherCubes config and apply it and everything will change?

**Comment by reesericci** [comment]
Doesn't this change the background though? I don't think its currently possible to change the background in the config. @WitherCubes made changes to the core css files, and as such overrides the theme. If somebody wants to use this, they would have to build it themselves with the new css.

**Comment by reesericci** [comment]
image
yup core files being changed @deepjyoti30

**Comment by deepjyoti30** [comment]
@reesericci It does make sense to allow more theming options. I think we can open an issue and discuss about it over there instead of this PR?! Feel free to open one!

**Comment by WitherCubes** [comment]
We can give an option for the user to download the default theme or the nord theme.

**Pull request closed without merging**
