### PR TITLE
Added Nord theme for startpage

### PR DESCRIPTION
**Pull request by WitherCubes**

### CODE REVIEW

**Comment by reesericci** [comment]
Why are you PR'ing your bookmarks? Its not just the nord theme.

**Comment by reesericci** [comment]
And your custom README

**Comment by reesericci** [comment]
Look at the commits

**Comment by deepjyoti30** [comment]
@WitherCubes Great job on the theme, looks pretty good.

Also as @reesericci asked, why are you trying to merge your changes on the master branch? If you want, I can add a shoutout for your theme in the `README` but if I merge your changes those will just override the default theme since we do not have support for multiple themes or so.

**Comment by reesericci** [comment]
yeah

**Pull request closed without merging**
