### PR TITLE
add autofocus to #search-bar-input

### PR DESCRIPTION
**Pull request by wijaksanapanji**

### CODE REVIEW

**Comment by deepjyoti30** [comment]
Hey @wijaksanapanji Thanks for the PR.

I had already added a line of code in the JS to add focus to the search bar but it doesn't work because the browser overrides that to put the focus on the top bar instead.

So, did you try this implementation locally? An by locally I mean by installing the extension and checking if the focus is on the search bar if a new tab page is installed.?

Once you confirm that, I'll merge.

**Comment by wijaksanapanji** [comment]
@deepjyoti30 what I tried is clone the repo, edit the index.html and open the index.html on firefox and chrome, and it's seem to autofocus on the search input

**Comment by deepjyoti30** [comment]
@wijaksanapanji I'm sure that won't work since I'm already doing that from JS. Anyway, if you can test and confirm it's working I can still merge.

**Comment by wijaksanapanji** [comment]
@deepjyoti30 hmm you are right, I just notice that, sorry, I will close the PR.

**Pull request closed without merging**
